# Generated by Django 3.2.9 on 2021-11-30 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='genero',
            new_name='generos',
        ),
    ]
